server:
  servlet:
    context-path: /booking_notification

spring:

  mail:
    host: smtp.mail.ru
    port: 465
    username: ${email.server.user}
    password: ${email.server.password}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  jackson:
    serialization:
      write_dates_as_timestamps: false

integration:
  users:
    url: http://localhost:9003/booking_users

app:
  email:
    admin-email: ${admin.email}
  sms:
    twilio-account-sid: ${twilio.account.sid}
    twilio-auth-token: ${twilio.auth.token}
    twilio-phone-number: ${twilio.phone.number}
  message:
    capacity: 200
    polling-time: 2000

logging:
  level:
    ru.otus: debug
    org.springframework: debug
