spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/booking_room
    username: postgres
    password: postgres
    initialization-mode: always
    sql-script-encoding: utf-8
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:/db/migration/
    validate-on-migrate: true
    baseline-on-migrate: true
    out-of-order: true

  data:
    mongodb:
      host: localhost
      port: 27018
      database: booking_room

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  jackson:
    serialization:
      write_dates_as_timestamps: false

integration:
  service:
    users:
      url: http://localhost:9003/booking_users
    notification:
      url: http://localhost:9002/booking_notification
  auth:
    username: ${notification.username}
    password: ${notification.password}

app:
  audit:
    enabled: true
    listener: hibernate #spring, hibernate
  notify:
    enabled: true
  schedule:
    enabled: true
    complete-bookings-cron-expression: "0 0/1 * * * *"  #Every minute
    notify-bookings-cron-expression: "0 0/1 * * * *"    #Every minute

logging:
  level:
    ru.otus: debug
    org.springframework: debug

feign:
  hystrix:
    enabled: true
  client:
    config:
      users:
        connectTimeout: 10000
        readTimeout: 20000
      notification:
        connectTimeout: 10000
        readTimeout: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
      metrics.rollingStats.timeInMilliseconds: 10000
